default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'postgres') %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>


development:
  <<: *default
  database: onebislack_development
  host: <%= ENV.fetch("POSTGRES_HOST", 'postgres') %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>


test:
  <<: *default
  database: onebislack_exchance_test

production:
  <<: *default
  database: onebislack_exchance_production