# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9089c7a03807ad1f39c9374116a08cebedbd81ca497d195bbd49df71d93df3ec17c2d7a3bae100d876823c0a9c82a84fc5736e1a55ed68f29e13320f4d8c98e2

test:
  secret_key_base: a063b26d7404f18b19d9a5072323290c9c79dabc55f3b4d41eb075b9319e220c4d04d7cdd5bdcee2f0371c07c4b6c887506c24bf81cdf9cfd1de44e0fc0bbcdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
